### ISSUE TITLE
Dont,t work

### ISSUE THREAD

**Issue by DiegoBari** [lighttigerXIV/ulauncher-bookmarks#1]
Hello,
the extension save the data to bookmarks.json but is imposible to recover the link later.

Thansks

**Comment by TigBuh99** [comment]
Confirmed on MX Linux 23. Nothing is saved in .config.

**Comment by lighttigerXIV** [comment]
> Confirmed on MX Linux 23. Nothing is saved in .config.

That's weird. But I can't really debug since i don't have linux mint and I don't use ulauncher anymore

**Comment by TigBuh99** [comment]
Thank you for a quick reply.
