### ISSUE TITLE
Feature request: select what web browser to open the URL.

### ISSUE THREAD

**Issue by matheusunderline** [lighttigerXIV/ulauncher-bookmarks#2]
I don't know how many difficult you would have to development this feature, but would be so cool.

Anyway, if some moment you things this feature would useful, I am here to prove it.

Thank you to create the plugin. ❤️

**Comment by lighttigerXIV** [comment]
Do you mean to open all the links in the browser you specified or select the browser when you search for a bookmark?

**Comment by matheusunderline** [comment]
Hi, lighttigerXIV.

"select the browser when you search for a bookmark".

**Comment by lighttigerXIV** [comment]
IDK how i would be able to do this :\. I could only change the browser by a setting because depending on your browser it has some commands to search.

**Comment by lighttigerXIV** [comment]
And tbh i am making my own launcher and won't probably update this anymore.

**Comment by matheusunderline** [comment]
No problem, lighttigerXIV, anyway, thank you to make this plugin and others to ULauncher.

Good luck to develop you own Launcher, I am excited now to try out when it to be available possible.  :heart:
