### ISSUE TITLE
Copy instead of Open

### ISSUE THREAD

**Issue by 1094** [lighttigerXIV/ulauncher-bookmarks#4]
This extension is almost perfect for me, but, I switch between browsers (Tor and Mullvad), so, instead of opening the URL, I'd like to go to the clipboard.

I've been playing with the code a bit and I can't seem to get it to work. I don't know if asking you is the best thing (feel free to close this if it isn't), but I don't know where else to ask. I've tried the following (after importing the CopyToClipboardAction)-;

Attempt 1
```
if function == Function.OPEN:

CopyToClipboardAction(data["url"])

return HideWindowAction()
```

Attempt 2
```
if function == Function.OPEN:

url_to_copy = data["url"]
copy_action = CopyToClipboardAction(url_to_copy)
hide_action = HideWindowAction()

return [copy_action, hide_action]
```

Attempt 3
```
if function == Function.OPEN:

url_to_copy = data["url"]
subprocess.run(["wl-copy"], input=url_to_copy.encode(), text=True)

return HideWindowAction()
```

I can't help but think I'm missing something simple....

**Comment by lighttigerXIV** [comment]
@1094 The first attempt seems right. IDK if you you copy pasted it badly but it should have a identation:

```python
if function == Function.OPEN:
  CopyToClipboardAction(data["url"])
  return HideWindowAction()
```

And after you change the code you need to close all ulauncher processes and open it again so it loads the extension again.

**Comment by 1094** [comment]
Oh. I was using the option in Setting to reload them. I'll try that one again and kill it from btop.   
And, yes, the code does have the indents. 

Thanks so much for your time and help!
